apps_profile/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^edit/$', edit_profile, name ='edit_profile'),
	url(r'^set_user_data/$',set_user_data, name = 'set_user_data')
]

jobseeker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import apps_login.urls as apps_login
import apps_profile.urls as apps_profile
import apps_status.urls as apps_status
import apps_search.urls as apps_search
import apps_riwayat.urls as apps_riwayat

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(apps_login,namespace='login')),
    url(r'^status/', include(apps_status,namespace='status')),
    url(r'^profile/', include(apps_profile,namespace='profile')),
    url(r'^teman/', include(apps_search,namespace='teman')),
    url(r'^riwayat/', include(apps_riwayat,namespace='riwayat')),
    url(r'^$', RedirectView.as_view(url="/login/", permanent="true"), name='index'),
]

apps_profile/models.py
from django.db import models

# Create your models here.
class dataProfile(models.Model):
	username = models.CharField(max_length=20, primary_key= True)
	npm = models.CharField(max_length=20, unique=True)
	profile_picture = models.URLField(default = "http://www.contribcity.com/images/dummy-profile-pic.png")
	nama = models.CharField(max_length=50, default= "Kosong")
	expertise = models.CharField('Expertise', max_length=50)
	email = models.TextField(default="Kosong")
	linkedIn = models.TextField(default="Kosong")

class Expertise(models.Model):
	BEGINNER = 'Beginner'
	INTERMEDIATE = 'Intermediate'
	ADVANCE = 'Advance'
	EXPERT = 'Expert'

	LEVEL_CHOICE = (
		(BEGINNER,1),
		(INTERMEDIATE,2),
		(ADVANCE,3),
		(EXPERT,4)
	)

	def __str__ (self):
		return self.expertise

apps_profile/views.py
from django.shortcuts import render
from apps_login.models import User
from .models import dataProfile
from apps_status.models import StatusKu

# Create your views here.
response = {}
def index(request):
	if 'user_login' in request.session:
		set_data_for_session(request)
		kode_identitas = get_data_user(request, 'kode_identitas')
		try:
			pengguna = User.objects.get(kode_identitas = kode_identitas)
		except Exception as e:
			pengguna = create_new_user(request)
		response['test'] = 'hai halo'

		profile = dataProfile()
		response['nama'] = profile.nama
		response['keahlian'] = profile.expertise
		response['email'] = profile.email
		response['linkedin'] = profile.linkedIn
		html = 'profile/profile.html'
		set_data_for_session(request)
		kode_identitas = get_data_user(request, 'kode_identitas')
		pengguna = User.objects.get(kode_identitas = kode_identitas)

		statusdata = StatusKu()
		banyakstat = StatusKu.objects.filter(pengguna = pengguna).all().count()
		response['status'] = banyakstat

		if banyakstat > 0:
			response['status_akhir'] = StatusKu.objects.last().description
		else:
			response['status_akhir'] = "Tidak ada status terbaru"

		response['login'] = True
		html = 'profile/profile.html'

		profile = dataProfile()
		response['nama'] = profile.nama
		response['keahlian'] = profile.expertise
		response['email'] = profile.email
		response['linkedin'] = profile.linkedIn
		html = 'profile/profile.html'
		set_data_for_session(request)
		kode_identitas = get_data_user(request, 'kode_identitas')
		pengguna = User.objects.get(kode_identitas = kode_identitas)

		statusdata = StatusKu()
		banyakstat = StatusKu.objects.filter(pengguna = pengguna).all().count()
		response['status'] = banyakstat

		if banyakstat > 0:
			response['status_akhir'] = StatusKu.objects.last().description
		else:
			response['status_akhir'] = "Tidak ada status terbaru"

		return render(request, html, response)
	else:
		response['login'] = False
		html = 'login/login.html'
		return render(request, html, response)

### SESSION : GET and SET
def get_data_session(request):
	if get_data_user(request, 'user_login'):
		response['author'] = get_data_user(request, 'user_login')

def set_data_for_session(request):
	response['author'] = get_data_user(request, 'user_login')
	response['kode_identitas'] = request.session['kode_identitas']
	response['role'] = request.session['role']

def get_data_user(request, tipe):
	data = None
	if tipe == "user_login" and 'user_login' in request.session:
		data = request.session['user_login']
	elif tipe == "kode_identitas" and 'kode_identitas' in request.session:
		data = request.session['kode_identitas']
	elif tipe == "role" and 'role' in request.session:
		data = request.session['role']


	return data

def create_new_user(request):
	nama = get_data_user(request, 'user_login')
	kode_identitas = get_data_user(request, 'kode_identitas')
	role = get_data_user(request, 'role')
	pengguna = User()
	pengguna.kode_identitas = kode_identitas
	pengguna.role = role
	pengguna.nama = nama
	pengguna.save()

	return pengguna

def edit_profile(request):
	html = 'profile/edit.html'
	response['kode_identitas'] = get_data_user(request,'kode_identitas')
	return render(request,html,response)

def set_user_data(request):
	if request.method == 'POST':
		name = request.POST['name']
		email = request.POST['email']

		#bikin model
		# HELP

	return HttpResponseRedirect(reverse('profile:edit_profile'))

apps_profile/templates/profile/edit.html
{% extends "login/layout/base.html" %}

{%block content%}



<script type="text/javascript">
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }
    
    // Use the API call wrapper to request the member's profile data
    function getProfileData() {
        IN.API.Profile("me").fields("id", "first-name", "last-name", "headline", "location", "picture-url", "public-profile-url", "email-address").result(displayProfileData).error(onError);
    }

    // Handle the successful return from the API call
    function displayProfileData(data){
        var user = data.values[0];
        console.log("set user data");
        console.log("Nama: "+user.emailAddress);
            document.getElementById("picture").innerHTML = '<img src="'+user.pictureUrl+'" height="100" width="100" class="img-circle">';
            document.getElementById("name").innerHTML = 'Nama: '+user.firstName+' '+user.lastName;
            //document.getElementById("intro").innerHTML = user.headline;
            document.getElementById("email").innerHTML = 'E-mail: '+user.emailAddress;
            //document.getElementById("location").innerHTML = user.location.name;
            document.getElementById("link").innerHTML = '<a href="'+user.publicProfileUrl+'" target="_blank">Visit profile</a>';
            document.getElementById('profileData').style.display = 'block';
        // $.ajax({
        //     method: "POST",
        //     url: '{% url "profile:set_user_data" %}',
        //     data: {
        //         name = user.firstName,
        //         email = user.emailAddress
        //     },
        //     dataType: 'json',
        //     success: function(user){
        //         console.log("Nama: "+user.firstName);
        //     },
        //     error: function(error){
        //         alert("Antara fungsinya belom bikin, atau linked in cari perkara");
        //     }
        // });
    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }
    
    // Destroy the session of linkedin
    function logout(){
        IN.User.logout(removeProfileData);
    }
    
    // Remove profile data from page
    function removeProfileData(){
        document.getElementById('profileData').remove();
    }

    function addSkill(){
        $('#user-skill').append('<table>'+
        '<tr style="padding: 10px 20px 10px 20px">'+
            '<th >'+
        '<select>'+
          '<option value="java">Java</option>'+
          '<option value="c++">C++</option>'+
          '<option value="python">Python</option>'+
        '</select>'+
            '</th>'+
          '<th style="padding: 10px 20px 10px 20px">Level:</th>'+
            '<th>'+
        '<select>'+
        '<option value="beginner">Beginner</option>'+
        '<option value="intermediate">Intermediate</option>'+
        '<option value="advance">Advance</option>'+
        '</select>'+
            '</th>'+
        '</tr>'+
    '</table>')
    }
</script>


<div class="container">
    <center>
    	<div id = "picture"></div>
    	<h4 id="npm"> {{ kode_identitas }} </h4>
    	<span><button onclick="">SIMPAN</button></span>
    	<span><button onclick="location.href='{% url 'profile:index' %}'">KELUAR</button></span>
    </center>
  <h2>Data Pribadi</h2>
  <div id="name">
    <script type="IN/Login"></script>
  </div>
  <div id="email"></div>
  
  <span>
    <p>Tampilkan nilai:</p>
    <input type="radio" id="akses-nilai" name ="nilai" value="no" checked="True"> Tidak
    <input type="radio" id="akses-nilai" name="nilai" value="yes"> Ya
  </span>
  
  <div id="user-bio"></div>
<table>
  <tr>
      <th><h2>Keahlian</h2></th>
      <th><button onclick="addSkill()" style="margin-left: 20px">+</button></th>
  </tr>
</table>
  <div id="user-skill">
    <table>
        <tr style="padding: 10px 20px 10px 20px">
            <th >
        <select>
          <option value="java">Java</option>
          <option value="c++">C++</option>
          <option value="python">Python</option>
        </select>
            </th>

            <th style="padding: 10px 20px 10px 20px">Level:</th>
            <th>
        <select>
        <option value="beginner">Beginner</option>
        <option value="intermediate">Intermediate</option>
        <option value="advance">Advance</option>
        </select>
            </th>
        </tr>
    </table>
  </div>
</div>
{% endblock %}

apps_profile/templates/profile/profile.html
{% extends "login/layout/base.html" %}

{% block content %}
<h1 style="text-align:left;"><strong>Selamat Datang, {{ author }}</strong></h1>
<table cellpadding="10">
	<tr>
		<td rowspan="2" style="padding-right:20px"><img src="http://www.contribcity.com/images/dummy-profile-pic.png" style="width: 200px"></td>
		<td align="center" style="padding-right:200px"><input type="button" value="Lihat Forum"></td>
		<td align="right" style="padding-right:200px"><h3>Jumlah Status: {{ status }} post</h3></td>
	</tr>
		<td style="padding-right:200px"><input type="button" value="Edit Profile" onclick="location.href='{% url 'profile:edit_profile' %}'"></td>
		<!-- <td><input type="button" value="Edit Profile"></td> -->
		<td style="padding-right:200px"><h3>{{ status_akhir }} </h3></td>
	</tr>	
</table>
<p></p>
<p></p>

<table cellpadding="5" cellspacing="5" href="#" data-toggle="popover" data-content="Silahkan isi profile anda!">
	<tr>
		<td align="left"><h4>Nama</h4></td>
		<td align="left"><h4>{{ nama }}</h4></td>
	</tr>
	<tr>
		<td align="left"><h4>NPM</h4></td>
		<td align="left"><h4>{{ kode_identitas }}</h4></td>
	</tr>
	<tr>
		<td align="left"><h4>Keahlian</h4></td>
		<td align="left"><h4>{{ keahlian }}</h4></td>
	</tr>
	<tr>
		<td align="left"><h4>Email</h4></td>
		<td align="left"><h4>{{ email }}</h4></td>
	</tr>
	<tr>
		<td align="left"><h4>Profile LinkedIn</h4></td>
		<td align="left"><h4>{{ linkedIn }} </td>
</table>
<!-- Content Here -->
<script>
	$(document).ready(function(){
    	$('[data-toggle="popover"]').popover();   
	});
</script>

{% endblock %}